// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-c0zYIOVducQnw8r01ZZmH-Ifh_VPILk',
    appId: '1:192604599741:web:ae920347b4bf70e1578ed4',
    messagingSenderId: '192604599741',
    projectId: 'electivagrupo2-37aad',
    authDomain: 'electivagrupo2-37aad.firebaseapp.com',
    storageBucket: 'electivagrupo2-37aad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWM7rMdSOWXpv-lD-JcKOCbJ8W4eIv4p8',
    appId: '1:192604599741:android:1d7163c007d9e0b6578ed4',
    messagingSenderId: '192604599741',
    projectId: 'electivagrupo2-37aad',
    storageBucket: 'electivagrupo2-37aad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbgNCI3CD5X3FVY98tNqRR8cnt8YeVNHg',
    appId: '1:192604599741:ios:4889e357e7ed193d578ed4',
    messagingSenderId: '192604599741',
    projectId: 'electivagrupo2-37aad',
    storageBucket: 'electivagrupo2-37aad.firebasestorage.app',
    iosBundleId: 'com.example.talleresmoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbgNCI3CD5X3FVY98tNqRR8cnt8YeVNHg',
    appId: '1:192604599741:ios:4889e357e7ed193d578ed4',
    messagingSenderId: '192604599741',
    projectId: 'electivagrupo2-37aad',
    storageBucket: 'electivagrupo2-37aad.firebasestorage.app',
    iosBundleId: 'com.example.talleresmoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-c0zYIOVducQnw8r01ZZmH-Ifh_VPILk',
    appId: '1:192604599741:web:e252d3b237a5c312578ed4',
    messagingSenderId: '192604599741',
    projectId: 'electivagrupo2-37aad',
    authDomain: 'electivagrupo2-37aad.firebaseapp.com',
    storageBucket: 'electivagrupo2-37aad.firebasestorage.app',
  );
}
